network:
  ethernets: 
    enp6s0:
      addresses:
      - 192.168.1.2/24
      gateway4: 192.168.1.1
      nameservers:
        addresses: [8.8.4.4, 8.8.8.8]
      optional: true
  version: 2
  renderer: networkd

